spring.application.name=simpleweather

weather.api.forecast-base-url=https://api.open-meteo.com/v1
weather.api.geocoding-base-url=https://geocoding-api.open-meteo.com/v1
weather.api.timeout-seconds=10

app.cors.allowed-origins=http://localhost:5173
